version: '3.8'

services:
  app:
    volumes:
      # Mount source code for development (live updates)
      - ./lib:/app/lib
      - ./app:/app/app
      - ./components:/app/components
      # Keep storage mount
      - ./storage:/app/storage
    environment:
      # Enable Next.js development features
      - NODE_ENV=development